name: Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel on failure
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C05P3UVCCLS"
          payload: |
            {
              "text": "main branch failed for tarpon!"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
